<?php echo $this->doctype() ?>
<?php //echo $this->placeholder('header'); ?>

<html>
    <head>
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Favicon -->
    
        <link rel="shortcut icon" href="/img/favicon.ico">
        <?php echo $this->headMeta() ?>
        <?php echo $this->headTitle() ?>

        <?php $this->headScript()->appendFile($this->baseUrl().'/js/jquery.js') ?>
        <?php $this->headScript()->appendFile($this->baseUrl().'/js/bootstrap.js') ?>
        <?php $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui.js') ?>
        <?php $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui-1.10.2.custom.js') ?>
        <?php $this->headScript()->appendFile($this->baseUrl().'/js/jquery.maskedinput.js') ?>
        <?php $this->headScript()->appendFile($this->baseUrl().'/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9')) ?>
        
        <?php echo $this->headScript() ?>

        <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/jquery-ui.css', 'screen') ?>
        <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/bootstrap.css', 'screen') ?>
        <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/font-awesome.css', 'screen') ?>
        <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/font-awesome-ie7.min.css', 'screen', 'IE 7') ?>
        <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/global.css', 'screen') ?>
        <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/bootstrap-responsive.css', 'screen') ?>
        
        <?php echo $this->headLink() ?>
    </head>
    <body>
        <!-- Modal -->
        <div id="about" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

                <h3 id="myModalLabel">Sistema de Controle de Acadêmia</h3>
            </div>

            <div class="modal-body">
                <p>Sistema para controle de academia open-source</p>

                <p><strong>Autor:</strong> Welsiton Ferreira (<a href="http://www.wfcreations.com.br/">WF Creations</a>)</p>
            </div>

            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">OK</button>
            </div>
        </div>

        <div class="container">
            <div class="header">
                <div class="navbar navbar-fixed-top">
                    <div class="navbar-inner">
                        <div class="container">
                            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="brand">Controle de Academia</a>
                            <div class="nav-collapse collapse">
                                <ul class="nav">
                                    <!-- viewHelper url  one of the best veiew helpers-->
                                    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index'), null, true) ?>"><i class="icon-home"></i> Início</a></li>
                                    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'authentication', 'action' => 'logout'), null, true) ?>"><i class="icon-logout"></i> Logout</a></li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-pencil"></i> Cadastro <b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="<?php echo $this->url(array('controller' => 'customer', 'action' => 'create'), null, true) ?>">Alunos</a></li>
                                            <li><a href="<?php echo $this->url(array('controller' => 'employees', 'action' => 'create'), null, true) ?>">Funcionários</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-building"></i> Academia <b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="<?php echo $this->url(array('controller' => 'customer', 'action' => 'payment'), null, true) ?>">Pagamentos</a></li>
                                            <li><a href="<?php echo $this->url(array('controller' => 'customer', 'action' => 'index'), null, true) ?>">Controle de Alunos</a></li>
                                            <li><a href="<?php echo $this->url(array('controller' => 'employees', 'action' => 'index'), null, true) ?>">Controle de Funcionários</a></li>
                                            <li><a href="#">Controle de Acesso</a></li>
                                             <li><a href="#"></a></li>
                                            
                                        </ul>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-money"></i> Caixa <b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="#">Históricos de Pagamento</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" data-toggle="modal" data-target="#about"><i class="icon-info-sign"></i> Sobre</a></li>
                                </ul>
                                <ul class="nav pull-right">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i> Entrar <b class="caret"></b></a>
                                        <form class="login-menu dropdown-menu well">
                                            <?php// echo $this->partial('partials/login.phtml', array('users' => $this->header)); ?>
                                            <?php echo $this->form; ?>
                                         
                                        </form>
                                    </li>
                                </ul>
                            </div><!--/.nav-collapse -->
                        </div><!--/.container -->
                    </div><!--/.navbar-inner -->
                </div><!--/.navbar -->
            </div>