<?php echo $this->render('_header.phtml') ?>



<div class="content">
    <!--
    Zend layout is going to render the dynamic content from the controller
    and the viewer inside of layout instances content variable = layout()->content
    -->
    <div id="categories">
		<?php echo $this->partial('partials/categories.phtml', array('categories' => $this->data)); ?>
	</div>
    <?php echo $this->layout()->content; ?>
</div>

<?php echo $this->render('_footer.phtml') ?>