<?php echo $this->render('_header.phtml') ?>

<div id="menu" style="background-color:#FFD700;height:520px ;width:140px;float:left;"><br>
    <br>
<b align="center">Menu</b><br>
<?php echo $this->navigation(); ?>
</div>
    
<div  class="content">
    <!--
    Zend layout is going to render the dynamic content from the controller
    and the viewer inside of layout instances content variable = layout()->content
    -->
   
    <?php echo $this->layout()->content; ?>
</div>

<?php echo $this->render('_footer.phtml') ?>